# Feature Pipeline – explicit directories

In [5]:
import os, datetime, glob, pyspark
from pyspark.sql import functions as F
from utils.feed_configs import FEEDS
import utils.bronze_generic as bronze
import utils.silver_generic as silver
import utils.gold_feature_store as gold_feat

spark = (pyspark.sql.SparkSession.builder
           .appName('feature_pipeline')
           .master('local[*]').getOrCreate())
spark.sparkContext.setLogLevel('ERROR')

In [6]:
csv_list = ["./data/feature_clickstream.csv", "./data/features_attributes.csv", "./data/features_financials.csv"]


bronze_root_directory  = ["datamart/bronze/clickstream/", "datamart/bronze/attributes/", "datamart/bronze/financials/"]
silver_root_directory  = ["datamart/silver/clickstream/", "datamart/silver/attributes/", "datamart/silver/financials/"]
gold_feature_directory = ["datamart/gold/feature_store/"] 

for d in bronze_root_directory + silver_root_directory + gold_feature_directory:
    os.makedirs(d, exist_ok=True)

In [7]:

def first_of_month(start='2023-01-01', end='2024-12-01'):
    cur=datetime.datetime.strptime(start,'%Y-%m-%d')
    end=datetime.datetime.strptime(end,'%Y-%m-%d')
    while cur<=end:
        yield cur.strftime('%Y-%m-%d')
        cur=(cur.replace(day=1)+datetime.timedelta(days=32)).replace(day=1)


dates_str_lst=list(first_of_month())
dates_str_lst

['2023-01-01',
 '2023-02-01',
 '2023-03-01',
 '2023-04-01',
 '2023-05-01',
 '2023-06-01',
 '2023-07-01',
 '2023-08-01',
 '2023-09-01',
 '2023-10-01',
 '2023-11-01',
 '2023-12-01',
 '2024-01-01',
 '2024-02-01',
 '2024-03-01',
 '2024-04-01',
 '2024-05-01',
 '2024-06-01',
 '2024-07-01',
 '2024-08-01',
 '2024-09-01',
 '2024-10-01',
 '2024-11-01',
 '2024-12-01']

In [8]:


bronze.backfill_bronze_dates(dates_str_lst, csv_list, bronze_root_directory, spark)

2023-01-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_01_01.csv
2023-02-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_02_01.csv
2023-03-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_03_01.csv
2023-04-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_04_01.csv
2023-05-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_05_01.csv
2023-06-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_06_01.csv
2023-07-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_07_01.csv
2023-08-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_08_01.csv
2023-09-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_09_01.csv
2023-10-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_10_01.csv
2023-11-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_11_01.csv
2023-12-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_12_01.csv
2024-01-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_01_01.csv
2024-02-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_02_01.csv
2024-03-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_03_01.csv
2024-04-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_04_01.csv
2024-05-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_05_01.csv
2024-06-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_06_01.csv
2024-07-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_07_01.csv
2024-08-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_08_01.csv
2024-09-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_09_01.csv
2024-10-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_10_01.csv
2024-11-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_11_01.csv
2024-12-01 row count: 8974
Saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_12_01.csv
2023-01-01 row count: 530
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_01_01.csv
2023-02-01 row count: 501
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_02_01.csv
2023-03-01 row count: 506
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_03_01.csv
2023-04-01 row count: 510
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_04_01.csv
2023-05-01 row count: 521
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_05_01.csv
2023-06-01 row count: 517
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_06_01.csv
2023-07-01 row count: 471
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_07_01.csv
2023-08-01 row count: 481
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_08_01.csv
2023-09-01 row count: 454
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_09_01.csv
2023-10-01 row count: 487
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_10_01.csv
2023-11-01 row count: 491
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_11_01.csv
2023-12-01 row count: 489
Saved to: datamart/bronze/attributes/bronze_features_attributes_2023_12_01.csv
2024-01-01 row count: 485
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_01_01.csv
2024-02-01 row count: 518
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_02_01.csv
2024-03-01 row count: 511
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_03_01.csv
2024-04-01 row count: 513
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_04_01.csv
2024-05-01 row count: 491
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_05_01.csv
2024-06-01 row count: 498
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_06_01.csv
2024-07-01 row count: 505
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_07_01.csv
2024-08-01 row count: 543
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_08_01.csv
2024-09-01 row count: 493
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_09_01.csv
2024-10-01 row count: 456
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_10_01.csv
2024-11-01 row count: 488
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_11_01.csv
2024-12-01 row count: 515
Saved to: datamart/bronze/attributes/bronze_features_attributes_2024_12_01.csv
2023-01-01 row count: 530
Saved to: datamart/bronze/financials/bronze_features_financials_2023_01_01.csv
2023-02-01 row count: 501
Saved to: datamart/bronze/financials/bronze_features_financials_2023_02_01.csv
2023-03-01 row count: 506
Saved to: datamart/bronze/financials/bronze_features_financials_2023_03_01.csv
2023-04-01 row count: 510
Saved to: datamart/bronze/financials/bronze_features_financials_2023_04_01.csv
2023-05-01 row count: 521
Saved to: datamart/bronze/financials/bronze_features_financials_2023_05_01.csv
2023-06-01 row count: 517
Saved to: datamart/bronze/financials/bronze_features_financials_2023_06_01.csv
2023-07-01 row count: 471
Saved to: datamart/bronze/financials/bronze_features_financials_2023_07_01.csv
2023-08-01 row count: 481
Saved to: datamart/bronze/financials/bronze_features_financials_2023_08_01.csv
2023-09-01 row count: 454
Saved to: datamart/bronze/financials/bronze_features_financials_2023_09_01.csv
2023-10-01 row count: 487
Saved to: datamart/bronze/financials/bronze_features_financials_2023_10_01.csv
2023-11-01 row count: 491
Saved to: datamart/bronze/financials/bronze_features_financials_2023_11_01.csv
2023-12-01 row count: 489
Saved to: datamart/bronze/financials/bronze_features_financials_2023_12_01.csv
2024-01-01 row count: 485
Saved to: datamart/bronze/financials/bronze_features_financials_2024_01_01.csv
2024-02-01 row count: 518
Saved to: datamart/bronze/financials/bronze_features_financials_2024_02_01.csv
2024-03-01 row count: 511
Saved to: datamart/bronze/financials/bronze_features_financials_2024_03_01.csv
2024-04-01 row count: 513
Saved to: datamart/bronze/financials/bronze_features_financials_2024_04_01.csv
2024-05-01 row count: 491
Saved to: datamart/bronze/financials/bronze_features_financials_2024_05_01.csv
2024-06-01 row count: 498
Saved to: datamart/bronze/financials/bronze_features_financials_2024_06_01.csv
2024-07-01 row count: 505
Saved to: datamart/bronze/financials/bronze_features_financials_2024_07_01.csv
2024-08-01 row count: 543
Saved to: datamart/bronze/financials/bronze_features_financials_2024_08_01.csv
2024-09-01 row count: 493
Saved to: datamart/bronze/financials/bronze_features_financials_2024_09_01.csv
2024-10-01 row count: 456
Saved to: datamart/bronze/financials/bronze_features_financials_2024_10_01.csv
2024-11-01 row count: 488
Saved to: datamart/bronze/financials/bronze_features_financials_2024_11_01.csv
2024-12-01 row count: 515
Saved to: datamart/bronze/financials/bronze_features_financials_2024_12_01.csv

{('./data/feature_clickstream.csv',
  '2023-01-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2023-02-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2023-03-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2023-04-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2023-05-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2023-06-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2023-07-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2023-08-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2023-09-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2023-10-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2023-11-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2023-12-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-01-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-02-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-03-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-04-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-05-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-06-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-07-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-08-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-09-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-10-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-11-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/feature_clickstream.csv',
  '2024-12-01'): DataFrame[fe_1: int, fe_2: int, fe_3: int, fe_4: int, fe_5: int, fe_6: int, fe_7: int, fe_8: int, fe_9: int, fe_10: int, fe_11: int, fe_12: int, fe_13: int, fe_14: int, fe_15: int, fe_16: int, fe_17: int, fe_18: int, fe_19: int, fe_20: int, Customer_ID: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-01-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-02-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-03-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-04-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-05-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-06-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-07-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-08-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-09-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-10-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-11-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2023-12-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-01-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-02-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-03-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-04-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-05-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-06-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-07-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-08-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-09-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-10-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-11-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_attributes.csv',
  '2024-12-01'): DataFrame[Customer_ID: string, Name: string, Age: string, SSN: string, Occupation: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-01-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-02-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-03-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-04-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-05-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-06-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-07-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-08-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-09-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-10-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-11-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',
  '2023-12-01'): DataFrame[Customer_ID: string, Annual_Income: string, Monthly_Inhand_Salary: double, Num_Bank_Accounts: int, Num_Credit_Card: int, Interest_Rate: int, Num_of_Loan: string, Type_of_Loan: string, Delay_from_due_date: int, Num_of_Delayed_Payment: string, Changed_Credit_Limit: string, Num_Credit_Inquiries: double, Credit_Mix: string, Outstanding_Debt: string, Credit_Utilization_Ratio: double, Credit_History_Age: string, Payment_of_Min_Amount: string, Total_EMI_per_month: double, Amount_invested_monthly: string, Payment_Behaviour: string, Monthly_Balance: string, snapshot_date: date],
 ('./data/features_financials.csv',

-----------
# Rough
------------------

In [9]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
from sklearn.impute import SimpleImputer

# 1. Attribures 
------

In [ ]:
a_csv_dir = '/app/datamart/bronze/attributes/'

csv_paths = glob.glob(os.path.join(a_csv_dir, '*.csv'))
csv_files_glob = [os.path.basename(path) for path in csv_paths]
print("CSV files (glob):", a_csv_files)

CSV files (glob): ['bronze_features_attributes_2023_01_01.csv', 'bronze_features_attributes_2023_02_01.csv', 'bronze_features_attributes_2023_03_01.csv', 'bronze_features_attributes_2023_04_01.csv', 'bronze_features_attributes_2023_05_01.csv', 'bronze_features_attributes_2023_06_01.csv', 'bronze_features_attributes_2023_07_01.csv', 'bronze_features_attributes_2023_08_01.csv', 'bronze_features_attributes_2023_09_01.csv', 'bronze_features_attributes_2023_10_01.csv', 'bronze_features_attributes_2023_11_01.csv', 'bronze_features_attributes_2023_12_01.csv', 'bronze_features_attributes_2024_01_01.csv', 'bronze_features_attributes_2024_02_01.csv', 'bronze_features_attributes_2024_03_01.csv', 'bronze_features_attributes_2024_04_01.csv', 'bronze_features_attributes_2024_05_01.csv', 'bronze_features_attributes_2024_06_01.csv', 'bronze_features_attributes_2024_07_01.csv', 'bronze_features_attributes_2024_08_01.csv', 'bronze_features_attributes_2024_09_01.csv', 'bronze_features_attributes_2024_10_01.csv', 'bronze_features_attributes_2024_11_01.csv', 'bronze_features_attributes_2024_12_01.csv']

In [17]:
# 1. Locate all CSV files
csv_dir = '/app/datamart/bronze/attributes/'
csv_paths = glob.glob(os.path.join(csv_dir, '*.csv'))

# 2. Prepare accumulators
missing_counts = None
zero_counts    = None
total_rows     = 0
dtypes         = None


# 3. Loop through each file
for path in csv_paths:
    df = pd.read_csv(path)
    total_rows += len(df)
    
    # capture dtypes once
    if dtypes is None:
        dtypes = df.dtypes.astype(str)
    
    # count missing (NaN) per column
    miss = df.isna().sum()
    missing_counts = miss if missing_counts is None else missing_counts.add(miss, fill_value=0)
    
    # count zeros in numeric columns
    nums = df.select_dtypes(include=[np.number])
    zero = (nums == 0).sum()
    zero_counts = zero if zero_counts is None else zero_counts.add(zero, fill_value=0)

# 4. Build summary DataFrame
summary = pd.DataFrame({
    'dtype':    dtypes,
    'missing':  missing_counts.astype(int),
    'zeros':    zero_counts.reindex(dtypes.index, fill_value=0).astype(int),
})

# 5. (Optional) add percent‐missing
summary['pct_missing'] = summary['missing'] / total_rows * 100

# 6. Display
print(f"Processed {len(csv_paths)} files, {total_rows} total rows\n")
print(summary)

Processed 24 files, 11974 total rows

                dtype  missing  zeros  pct_missing
Customer_ID    object        0      0          0.0
Name           object        0      0          0.0
Age            object        0      0          0.0
SSN            object        0      0          0.0
Occupation     object        0      0          0.0
snapshot_date  object        0      0          0.0

In [18]:
# Read and show the first file
if csv_paths:
    first_csv = csv_paths[0]
    df_first = pd.read_csv(first_csv)
    print(f"First CSV file: {first_csv}\n")
    print(df_first.head())
else:
    print("No CSV files found in", csv_dir)

First CSV file: /app/datamart/bronze/attributes/bronze_features_attributes_2023_01_01.csv

  Customer_ID             Name Age          SSN  Occupation snapshot_date
0  CUS_0x1037         Matthewm  45  230-22-9583  Accountant    2023-01-01
1  CUS_0x1069  Andreas Cremero  32  761-27-5143  Accountant    2023-01-01
2  CUS_0x114a    Valetkevitchu  43  133-89-5234   Developer    2023-01-01
3  CUS_0x1184           Cohenq  49  963-76-2464      Lawyer    2023-01-01
4  CUS_0x1297         Edwardsz  46    #F%$D@*&8     Manager    2023-01-01

## Silver generaic 
------

In [ ]:
import os
import glob
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, regexp_replace, when, lit, to_date
from pyspark.sql.types import StringType, IntegerType, DateType


def enforce_schema(df):
    """
    Casts columns to the desired types and applies basic cleaning.
    """
    # 1. Clean SSN: remove any characters except digits and hyphens
    df = df.withColumn(
        "SSN",
        regexp_replace(col("SSN"), r"[^0-9\-]", "")
    )
    
    # 2. Define desired schema
    column_type_map = {
        "Customer_ID": StringType(),
        "Name":        StringType(),
        "Age":         IntegerType(),
        "SSN":         StringType(),
        "Occupation":  StringType(),
        "snapshot_date": DateType(),
    }
    
    # 3. Apply casts
    for column, new_type in column_type_map.items():
        if isinstance(new_type, DateType):
            # parse date strings into DateType
            df = df.withColumn(column, to_date(col(column), "yyyy-MM-dd"))
        else:
            df = df.withColumn(column, col(column).cast(new_type))
    
    return df

-----
## Silver generaic

In [23]:
df_list = []
for path in csv_paths:
    df_raw = spark.read.csv(path, header=True, inferSchema=False)
    df_clean = enforce_schema(df_raw)
    df_list.append(df_clean)

In [24]:
for df in df_list:
    df.printSchema()
    df.show(3, truncate=False)

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+---------------+---+-----------+----------+-------------+
|Customer_ID|Name           |Age|SSN        |Occupation|snapshot_date|
+-----------+---------------+---+-----------+----------+-------------+
|CUS_0x1037 |Matthewm       |45 |230-22-9583|Accountant|2023-01-01   |
|CUS_0x1069 |Andreas Cremero|32 |761-27-5143|Accountant|2023-01-01   |
|CUS_0x114a |Valetkevitchu  |43 |133-89-5234|Developer |2023-01-01   |
+-----------+---------------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-----------------+---+-----------+----------+-------------+
|Customer_ID|Name             |Age|SSN        |Occupation|snapshot_date|
+-----------+-----------------+---+-----------+----------+-------------+
|CUS_0x10aa |Carey Gillama    |20 |101-00-4424|Musician  |2023-02-01   |
|CUS_0x113e |Ransdell Piersono|45 |542-14-0249|Manager   |2023-02-01   |
|CUS_0x1140 |Jennifer Sabal   |31 |141-17-2233|Accountant|2023-02-01   |
+-----------+-----------------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+---------+---+-----------+----------+-------------+
|Customer_ID|Name     |Age|SSN        |Occupation|snapshot_date|
+-----------+---------+---+-----------+----------+-------------+
|CUS_0x10bb |Chyenf   |35 |075-30-4340|Journalist|2023-03-01   |
|CUS_0x10eb |Yaob     |51 |8          |Journalist|2023-03-01   |
|CUS_0x1132 |Jonathano|39 |152-95-7926|Mechanic  |2023-03-01   |
+-----------+---------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-------------+---+-----------+------------+-------------+
|Customer_ID|Name         |Age|SSN        |Occupation  |snapshot_date|
+-----------+-------------+---+-----------+------------+-------------+
|CUS_0x1056 |Hornbyb      |44 |081-93-4350|Entrepreneur|2023-04-01   |
|CUS_0x11fc |Dmitracovaa  |30 |092-20-3138|Lawyer      |2023-04-01   |
|CUS_0x1216 |Robin Emmotti|19 |256-37-5248|Engineer    |2023-04-01   |
+-----------+-------------+---+-----------+------------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-----------------+---+-----------+----------+-------------+
|Customer_ID|Name             |Age|SSN        |Occupation|snapshot_date|
+-----------+-----------------+---+-----------+----------+-------------+
|CUS_0x1000 |Alistair Barrf   |18 |913-74-1218|Lawyer    |2023-05-01   |
|CUS_0x108a |Silvial          |38 |394-00-8142|Journalist|2023-05-01   |
|CUS_0x10f9 |Gilles Guillaumev|54 |746-79-6875|_______   |2023-05-01   |
+-----------+-----------------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-------------+----+-----------+----------+-------------+
|Customer_ID|Name         |Age |SSN        |Occupation|snapshot_date|
+-----------+-------------+----+-----------+----------+-------------+
|CUS_0x1044 |Maki Shirakip|44  |8          |_______   |2023-06-01   |
|CUS_0x104e |Kentaros     |50  |837-93-5062|Teacher   |2023-06-01   |
|CUS_0x105c |Lopezz       |4746|998-18-7252|Journalist|2023-06-01   |
+-----------+-------------+----+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+---------------+----+-----------+----------+-------------+
|Customer_ID|Name           |Age |SSN        |Occupation|snapshot_date|
+-----------+---------------+----+-----------+----------+-------------+
|CUS_0x1130 |Elizabethr     |37  |846-60-3664|_______   |2023-07-01   |
|CUS_0x11d1 |Jennifer Ablans|25  |8          |Mechanic  |2023-07-01   |
|CUS_0x11eb |Millikenw      |3553|032-85-4630|_______   |2023-07-01   |
+-----------+---------------+----+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+------------+----+-----------+----------+-------------+
|Customer_ID|Name        |Age |SSN        |Occupation|snapshot_date|
+-----------+------------+----+-----------+----------+-------------+
|CUS_0x1015 |Holtono     |27  |810-97-7024|Journalist|2023-08-01   |
|CUS_0x1032 |Wahbap      |NULL|620-58-8045|Lawyer    |2023-08-01   |
|CUS_0x106f |Alwyn Scottk|55  |517-96-1022|Developer |2023-08-01   |
+-----------+------------+----+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+---------------+----+-----------+-------------+-------------+
|Customer_ID|Name           |Age |SSN        |Occupation   |snapshot_date|
+-----------+---------------+----+-----------+-------------+-------------+
|CUS_0x1057 |David Sheppardv|NULL|741-07-3912|Writer       |2023-09-01   |
|CUS_0x1169 |Janeman Latulb |34  |352-87-0792|Lawyer       |2023-09-01   |
|CUS_0x117d |Evat           |24  |812-62-8349|Media_Manager|2023-09-01   |
+-----------+---------------+----+-----------+-------------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-------+---+-----------+----------+-------------+
|Customer_ID|Name   |Age|SSN        |Occupation|snapshot_date|
+-----------+-------+---+-----------+----------+-------------+
|CUS_0x1026 |Josephv|52 |500-62-9044|Manager   |2023-10-01   |
|CUS_0x109b |Gillesy|55 |661-04-3699|Manager   |2023-10-01   |
|CUS_0x10ff |Murait |36 |149-03-5931|Accountant|2023-10-01   |
+-----------+-------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-----------------+---+-----------+----------+-------------+
|Customer_ID|Name             |Age|SSN        |Occupation|snapshot_date|
+-----------+-----------------+---+-----------+----------+-------------+
|CUS_0x1011 |Schneyerh        |44 |793-05-8223|Doctor    |2023-11-01   |
|CUS_0x1018 |Felsenthalq      |15 |731-19-8119|Accountant|2023-11-01   |
|CUS_0x1041 |Jonathan Stempela|15 |675-80-2033|Teacher   |2023-11-01   |
+-----------+-----------------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+---------------+---+-----------+----------+-------------+
|Customer_ID|Name           |Age|SSN        |Occupation|snapshot_date|
+-----------+---------------+---+-----------+----------+-------------+
|CUS_0x1013 |Cameront       |44 |930-49-9615|Mechanic  |2023-12-01   |
|CUS_0x104a |Leahk          |37 |8          |Mechanic  |2023-12-01   |
|CUS_0x1063 |Sylvia Westallq|20 |883-38-8680|Architect |2023-12-01   |
+-----------+---------------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+----------------+---+-----------+------------+-------------+
|Customer_ID|Name            |Age|SSN        |Occupation  |snapshot_date|
+-----------+----------------+---+-----------+------------+-------------+
|CUS_0x102d |Neil Chatterjeex|31 |692-71-7552|Entrepreneur|2024-01-01   |
|CUS_0x1051 |Lucia Mutikanin |42 |232-33-7638|Engineer    |2024-01-01   |
|CUS_0x1269 |Chadbournk      |22 |755-70-8952|Manager     |2024-01-01   |
+-----------+----------------+---+-----------+------------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+----------------+---+-----------+----------+-------------+
|Customer_ID|Name            |Age|SSN        |Occupation|snapshot_date|
+-----------+----------------+---+-----------+----------+-------------+
|CUS_0x1048 |Janet McGurtyg  |27 |808-81-2470|Accountant|2024-02-01   |
|CUS_0x10c0 |Scheyderx       |39 |658-53-1756|Architect |2024-02-01   |
|CUS_0x115c |Ryan Vlastelicar|20 |956-28-3067|Engineer  |2024-02-01   |
+-----------+----------------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-------------+----+-----------+-------------+-------------+
|Customer_ID|Name         |Age |SSN        |Occupation   |snapshot_date|
+-----------+-------------+----+-----------+-------------+-------------+
|CUS_0x100b |Shirboni     |19  |8          |Media_Manager|2024-03-01   |
|CUS_0x1096 |Edward Krudyk|43  |228-65-4194|Lawyer       |2024-03-01   |
|CUS_0x111c |Deepaa       |NULL|420-66-8144|Journalist   |2024-03-01   |
+-----------+-------------+----+-----------+-------------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+------+---+-----------+----------+-------------+
|Customer_ID|Name  |Age|SSN        |Occupation|snapshot_date|
+-----------+------+---+-----------+----------+-------------+
|CUS_0x102e |Rhysn |26 |8          |Scientist |2024-04-01   |
|CUS_0x109d |Langep|45 |260-21-1290|Writer    |2024-04-01   |
|CUS_0x112e |Sanog |32 |981-03-7949|Mechanic  |2024-04-01   |
+-----------+------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+--------+---+-----------+-------------+-------------+
|Customer_ID|Name    |Age|SSN        |Occupation   |snapshot_date|
+-----------+--------+---+-----------+-------------+-------------+
|CUS_0x1075 |Dorfmanv|39 |225-94-8383|Manager      |2024-05-01   |
|CUS_0x1185 |Groverj |25 |238-50-2115|Accountant   |2024-05-01   |
|CUS_0x1190 |Toonkelc|45 |8          |Media_Manager|2024-05-01   |
+-----------+--------+---+-----------+-------------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+---------------+---+-----------+------------+-------------+
|Customer_ID|Name           |Age|SSN        |Occupation  |snapshot_date|
+-----------+---------------+---+-----------+------------+-------------+
|CUS_0x10dd |Praveen Menonq |25 |907-60-4113|Teacher     |2024-06-01   |
|CUS_0x1109 |Karen Freifeldf|43 |410-39-6091|Lawyer      |2024-06-01   |
|CUS_0x1286 |David Alexo    |813|456-37-9366|Entrepreneur|2024-06-01   |
+-----------+---------------+---+-----------+------------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-----------+---+-----------+----------+-------------+
|Customer_ID|Name       |Age|SSN        |Occupation|snapshot_date|
+-----------+-----------+---+-----------+----------+-------------+
|CUS_0x1108 |en Klaymano|25 |183-66-5001|Accountant|2024-07-01   |
|CUS_0x13b5 |Tim Reids  |54 |023-34-9301|Lawyer    |2024-07-01   |
|CUS_0x13b8 |ill Rigbyb |29 |094-65-0795|Scientist |2024-07-01   |
+-----------+-----------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-----------+---+-----------+----------+-------------+
|Customer_ID|Name       |Age|SSN        |Occupation|snapshot_date|
+-----------+-----------+---+-----------+----------+-------------+
|CUS_0x10ac |Zhouy      |29 |780-50-4730|Developer |2024-08-01   |
|CUS_0x10c5 |Moony      |24 |041-74-6785|_______   |2024-08-01   |
|CUS_0x1145 |Blenkinsopr|24 |426-31-9194|Teacher   |2024-08-01   |
+-----------+-----------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+---------+---+-----------+----------+-------------+
|Customer_ID|Name     |Age|SSN        |Occupation|snapshot_date|
+-----------+---------+---+-----------+----------+-------------+
|CUS_0x1087 |Alistairy|51 |620-14-7570|Doctor    |2024-09-01   |
|CUS_0x1138 |Prodhanx |44 |832-92-6672|Lawyer    |2024-09-01   |
|CUS_0x121b |Cheeu    |42 |162-52-8159|Architect |2024-09-01   |
+-----------+---------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+------------+---+-----------+----------+-------------+
|Customer_ID|Name        |Age|SSN        |Occupation|snapshot_date|
+-----------+------------+---+-----------+----------+-------------+
|CUS_0x1038 |B.h         |28 |355-00-7832|Architect |2024-10-01   |
|CUS_0x104f |Markm       |20 |264-84-8069|_______   |2024-10-01   |
|CUS_0x10a9 |ini Kristenr|41 |514-08-4156|Journalist|2024-10-01   |
+-----------+------------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+----------------+---+-----------+----------+-------------+
|Customer_ID|Name            |Age|SSN        |Occupation|snapshot_date|
+-----------+----------------+---+-----------+----------+-------------+
|CUS_0x107e |Lianaj          |15 |463-69-6790|Architect |2024-11-01   |
|CUS_0x10b3 |Johnsona        |48 |293-45-3004|Mechanic  |2024-11-01   |
|CUS_0x10df |Paritosh Bansalo|27 |279-20-3097|Musician  |2024-11-01   |
+-----------+----------------+---+-----------+----------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+----------+---+-----------+----------+-------------+
|Customer_ID|Name      |Age|SSN        |Occupation|snapshot_date|
+-----------+----------+---+-----------+----------+-------------+
|CUS_0x103e |Tim Kellyf|40 |155-72-8070|Scientist |2024-12-01   |
|CUS_0x1195 |Alexk     |31 |822-48-3629|Manager   |2024-12-01   |
|CUS_0x1197 |Nayako    |28 |799-23-8283|_______   |2024-12-01   |
+-----------+----------+---+-----------+----------+-------------+
only showing top 3 rows

In [25]:
# 1. Compute row counts for each DataFrame in df_list
row_counts = [df.count() for df in df_list]



# 3. Sum up all rows
total_rows = sum(row_counts)
print(f"Total rows across all files: {total_rows}")

Total rows across all files: 11974

In [26]:
df_all = df_list[0]
for df in df_list[1:]:
    df_all = df_all.union(df)

# 2. Summary statistics for Age
print("=== Age Summary Statistics ===")
df_all.select("Age").describe().show()

# 3. Total row count
total_rows = df_all.count()

# 4. Compute duplicates for each column
dup_stats = []
for col_name in ["Customer_ID", "snapshot_date", "SSN"]:
    distinct_count = df_all.select(col_name).distinct().count()
    dup_count = total_rows - distinct_count
    dup_stats.append((col_name, distinct_count, dup_count))

# 5. Display duplicate statistics
print("=== Duplicate Value Summary ===")
print(f"Total rows across all files: {total_rows}\n")
print(f"{'Column':<15} {'Distinct':>10} {'Duplicates':>12}")
for col_name, distinct_count, dup_count in dup_stats:
    print(f"{col_name:<15} {distinct_count:>10} {dup_count:>12}")

=== Age Summary Statistics ===
+-------+------------------+
|summary|               Age|
+-------+------------------+
|  count|             11358|
|   mean|104.88131713329811|
| stddev| 662.1956427656659|
|    min|              -500|
|    max|              8678|
+-------+------------------+

=== Duplicate Value Summary ===
Total rows across all files: 11974

Column            Distinct   Duplicates
Customer_ID          11974            0
snapshot_date           24        11950
SSN                  11299          675

In [31]:
from pyspark.sql.functions import col

# Assuming df_all_labeled is the combined DataFrame after labeling out‐of‐range Ages to 0:

# 1. Count nulls in Age
null_age = df_all_labeled.filter(col("Age").isNull()).count()
print(f"Null values in Age: {null_age}")

# 2. (Optional) Count nulls for every column
null_counts = {
    c: df_all_labeled.filter(col(c).isNull()).count()
    for c in df_all_labeled.columns
}
print("\nNull values per column:")
for column, count in null_counts.items():
    print(f"{column}: {count}")

Null values in Age: 616

Null values per column:
Customer_ID: 0
Name: 0
Age: 616
SSN: 0
Occupation: 0
snapshot_date: 0

In [29]:
from pyspark.sql.functions import when, col, lit

# Apply to each DataFrame in df_list:
df_list_labeled = [
    df.withColumn(
        "Age",
        when((col("Age") < 15) | (col("Age") > 100), lit(0))
        .otherwise(col("Age"))
    )
    for df in df_list
]

# (Optional) Re-union into a single DataFrame
df_all_labeled = df_list_labeled[0]
for df in df_list_labeled[1:]:
    df_all_labeled = df_all_labeled.union(df)

# Quick check: show distinct Age values
df_all_labeled.select("Age").distinct().orderBy("Age").show()

+----+
| Age|
+----+
|NULL|
|   0|
|  15|
|  16|
|  17|
|  18|
|  19|
|  20|
|  21|
|  22|
|  23|
|  24|
|  25|
|  26|
|  27|
|  28|
|  29|
|  30|
|  31|
|  32|
+----+
only showing top 20 rows

In [30]:
from pyspark.sql.functions import col

# Count rows where Age is outside the inclusive range 15 to 100
out_of_range_count = df_all.filter((col("Age") < 15) | (col("Age") > 110)).count()

print(f"Number of Age values outside the range 15–100: {out_of_range_count}")

Number of Age values outside the range 15–100: 373

In [32]:
from pyspark.sql.functions import col

# 1. Identify SSNs that appear more than once
dup_ssns = (
    df_all.groupBy("SSN")
          .count()
          .filter(col("count") > 1)
          .select("SSN")
)

# 2. Filter the full DataFrame to only those duplicate-SSN rows
df_ssn_duplicates = df_all.join(dup_ssns, on="SSN", how="inner")

# 3. Show the first few rows of the duplicates DataFrame
df_ssn_duplicates.show(5, truncate=False)

+---+-----------+-----------------+---+-------------+-------------+
|SSN|Customer_ID|Name             |Age|Occupation   |snapshot_date|
+---+-----------+-----------------+---+-------------+-------------+
|8  |CUS_0x1297 |Edwardsz         |46 |Manager      |2023-01-01   |
|8  |CUS_0x16f4 |Forgionez        |37 |Media_Manager|2023-01-01   |
|8  |CUS_0x1c9c |Dougq            |28 |Musician     |2023-01-01   |
|8  |CUS_0x2297 |Sergio Goncalvesc|43 |Teacher      |2023-01-01   |
|8  |CUS_0x2cae |Dunaiu           |28 |Journalist   |2023-01-01   |
+---+-----------+-----------------+---+-------------+-------------+
only showing top 5 rows

# Financials 
___

In [55]:
# point to your Bronze financials directory
fin_dir = "/app/datamart/bronze/financials/"
fin_paths = glob.glob(os.path.join(fin_dir, "*.csv"))
print("Financial CSVs:", [os.path.basename(p) for p in fin_paths])

Financial CSVs: ['bronze_features_financials_2023_01_01.csv', 'bronze_features_financials_2023_02_01.csv', 'bronze_features_financials_2023_03_01.csv', 'bronze_features_financials_2023_04_01.csv', 'bronze_features_financials_2023_05_01.csv', 'bronze_features_financials_2023_06_01.csv', 'bronze_features_financials_2023_07_01.csv', 'bronze_features_financials_2023_08_01.csv', 'bronze_features_financials_2023_09_01.csv', 'bronze_features_financials_2023_10_01.csv', 'bronze_features_financials_2023_11_01.csv', 'bronze_features_financials_2023_12_01.csv', 'bronze_features_financials_2024_01_01.csv', 'bronze_features_financials_2024_02_01.csv', 'bronze_features_financials_2024_03_01.csv', 'bronze_features_financials_2024_04_01.csv', 'bronze_features_financials_2024_05_01.csv', 'bronze_features_financials_2024_06_01.csv', 'bronze_features_financials_2024_07_01.csv', 'bronze_features_financials_2024_08_01.csv', 'bronze_features_financials_2024_09_01.csv', 'bronze_features_financials_2024_10_01.csv', 'bronze_features_financials_2024_11_01.csv', 'bronze_features_financials_2024_12_01.csv']

In [56]:
# ─── Block 2: Pandas Missing/Zero/Dtype Summary ────────────────────────────────
total_rows = 0
miss = zeros = None
dtypes = None

for path in fin_paths:
    df = pd.read_csv(path)
    total_rows += len(df)
    if dtypes is None:
        dtypes = df.dtypes.astype(str)
    miss   = df.isna().sum() if miss is None else miss.add(df.isna().sum(), fill_value=0)
    num    = df.select_dtypes(include=[np.number])
    zeros  = (num == 0).sum() if zeros is None else zeros.add((num == 0).sum(), fill_value=0)

summary = pd.DataFrame({
    "dtype":   dtypes,
    "missing": miss.astype(int),
    "zeros":   zeros.reindex(dtypes.index, fill_value=0).astype(int),
})
summary["pct_missing"] = summary["missing"] / total_rows * 100

print(f"Processed {len(fin_paths)} files, {total_rows} total rows")
display(summary)

Processed 24 files, 11974 total rows

                            dtype  missing  zeros  pct_missing
Customer_ID                object        0      0     0.000000
Annual_Income              object        0      0     0.000000
Monthly_Inhand_Salary     float64        0      0     0.000000
Num_Bank_Accounts           int64        0    519     0.000000
Num_Credit_Card             int64        0      4     0.000000
Interest_Rate               int64        0      0     0.000000
Num_of_Loan                object        0      0     0.000000
Type_of_Loan               object     1368      0    11.424754
Delay_from_due_date         int64        0    141     0.000000
Num_of_Delayed_Payment     object        0      0     0.000000
Changed_Credit_Limit       object        0      0     0.000000
Num_Credit_Inquiries      float64        0    517     0.000000
Credit_Mix                 object        0      0     0.000000
Outstanding_Debt           object        0      0     0.000000
Credit_Utilization_Ratio  float64        0      0     0.000000
Credit_History_Age         object        0      0     0.000000
Payment_of_Min_Amount      object        0      0     0.000000
Total_EMI_per_month       float64        0   1220     0.000000
Amount_invested_monthly    object        0      0     0.000000
Payment_Behaviour          object        0      0     0.000000
Monthly_Balance           float64        0      0     0.000000
snapshot_date              object        0      0     0.000000

In [57]:
# Assuming df is your DataFrame
# pd.set_option('display.max_columns', None) will show all columns
pd.set_option('display.max_columns', None)

# pd.set_option('display.width', None) can help with very wide DataFrames
# so that lines don't wrap prematurely, but it might not be strictly necessary
# for just showing all columns.
pd.set_option('display.width', None)

# ─── Block 3: Preview head() of First File ────────────────────────────────────
if fin_paths:
    df0 = pd.read_csv(fin_paths[0])
    print(f"--- {os.path.basename(fin_paths[0])} head() ---")
    display(df0.head())
else:
    print("No CSVs found in", fin_dir)

--- bronze_features_financials_2023_01_01.csv head() ---

,Customer_ID,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,snapshot_date
0,CUS_0x1037,15989.085,1086.423750,5,4,2,4,"Credit-Builder Loan, Auto Loan, Auto Loan, and...",13,15,0.5,3.0,Good,665.82,40.697699,19 Years and 9 Months,No,33.797021,80.46523951443457,Low_spent_Small_value_payments,284.380115,2023-01-01
1,CUS_0x1069,58637.34,4799.445000,4,6,10,119,"Personal Loan, Auto Loan, and Not Specified",9,17,12.56,5.0,Standard,208.8,25.233144,30 Years and 8 Months,Yes,139.885013,165.21061289035896,High_spent_Small_value_payments,434.848874,2023-01-01
2,CUS_0x114a,15305.46,1230.455000,0,7,2,2,"Student Loan, and Home Equity Loan",14,2,15.95,0.0,Good,642.42_,27.525113,15 Years and 9 Months,No,20.301654,64.77848007633177,Low_spent_Small_value_payments,327.965366,2023-01-01
3,CUS_0x1184,19867.475,1396.622917,3,5,11,3,"Student Loan, Mortgage Loan, and Payday Loan",10,9,6.74,4.0,Good,707.29,26.689790,32 Years and 8 Months,No,42.606882,23.460944042729498,!@9#%8,313.594466,2023-01-01
4,CUS_0x1297,57738.06_,4881.505000,9,8,30,9,"Payday Loan, Personal Loan, Payday Loan, Perso...",61,24,14.27,11.0,Bad,3916.47,25.742143,13 Years and 8 Months,Yes,296.284136,53.82117764831425,High_spent_Medium_value_payments,388.045187,2023-01-01

In [58]:
from pyspark.sql.functions import (
    col, to_date, regexp_replace, when, lit,
    regexp_extract, count as _count
)
from pyspark.sql.types import (
    StringType, IntegerType, FloatType, DateType
)



# ─── Block 4: Spark Session & Schema-Enforce Function ─────────────────────────
spark = SparkSession.builder.appName("BronzeToSilverFinancials").getOrCreate()

def enforce_schema_financials_raw(df):
    """
    1) Strip stray chars from numerics
    2) Cast all columns except Credit_History_Age and Payment_of_Min_Amount
       which remain raw strings for now.
    3) Parse snapshot_date as DateType.
    """
    # clean numeric-string columns of non-digits/dot
    clean_num = [
        "Annual_Income","Monthly_Inhand_Salary","Changed_Credit_Limit",
        "Outstanding_Debt","Credit_Utilization_Ratio",
        "Total_EMI_per_month","Amount_invested_monthly","Monthly_Balance"
    ]
    for c in clean_num:
        df = df.withColumn(c, regexp_replace(col(c), r"[^0-9\.]", ""))

    # schema mapping
    mapping = {
        "Customer_ID":              StringType(),
        "Annual_Income":            FloatType(),
        "Monthly_Inhand_Salary":    FloatType(),
        "Num_Bank_Accounts":        IntegerType(),
        "Num_Credit_Card":          IntegerType(),
        "Interest_Rate":            IntegerType(),
        "Num_of_Loan":              IntegerType(),
        "Type_of_Loan":             StringType(),
        "Delay_from_due_date":      IntegerType(),
        "Num_of_Delayed_Payment":   IntegerType(),
        "Changed_Credit_Limit":     FloatType(),
        "Num_Credit_Inquiries":     IntegerType(),
        "Credit_Mix":               StringType(),
        "Outstanding_Debt":         FloatType(),
        "Credit_Utilization_Ratio": FloatType(),
        "Total_EMI_per_month":      FloatType(),
        "Amount_invested_monthly":  FloatType(),
        "Payment_Behaviour":        StringType(),
        "Monthly_Balance":          FloatType(),
        "snapshot_date":            DateType(),
        # keep these raw:
        "Credit_History_Age":       StringType(),
        "Payment_of_Min_Amount":    StringType(),
    }
    for c, t in mapping.items():
        if isinstance(t, DateType):
            df = df.withColumn(c, to_date(col(c), "yyyy-MM-dd"))
        else:
            df = df.withColumn(c, col(c).cast(t))
    return df

In [59]:
# ─── Block 5: Read & Apply Schema Enforcement ─────────────────────────────────
df_list = []
for path in fin_paths:
    raw   = spark.read.csv(path, header=True, inferSchema=False)
    clean = enforce_schema_financials_raw(raw)
    df_list.append(clean)

In [60]:
# ─── Block 6: Preview Cleaned Schema & Samples ───────────────────────────────
for df in df_list:
    df.printSchema()
    df.show(3, truncate=False)

root
 |-- Customer_ID: string (nullable = true)
 |-- Annual_Income: float (nullable = true)
 |-- Monthly_Inhand_Salary: float (nullable = true)
 |-- Num_Bank_Accounts: integer (nullable = true)
 |-- Num_Credit_Card: integer (nullable = true)
 |-- Interest_Rate: integer (nullable = true)
 |-- Num_of_Loan: integer (nullable = true)
 |-- Type_of_Loan: string (nullable = true)
 |-- Delay_from_due_date: integer (nullable = true)
 |-- Num_of_Delayed_Payment: integer (nullable = true)
 |-- Changed_Credit_Limit: float (nullable = true)
 |-- Num_Credit_Inquiries: integer (nullable = true)
 |-- Credit_Mix: string (nullable = true)
 |-- Outstanding_Debt: float (nullable = true)
 |-- Credit_Utilization_Ratio: float (nullable = true)
 |-- Credit_History_Age: string (nullable = true)
 |-- Payment_of_Min_Amount: string (nullable = true)
 |-- Total_EMI_per_month: float (nullable = true)
 |-- Amount_invested_monthly: float (nullable = true)
 |-- Payment_Behaviour: string (nullable = true)
 |-- Monthly_Balance: float (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+---------------------+---------------------+-------------------+-----------------------+-------------------------------+---------------+-------------+
|Customer_ID|Annual_Income|Monthly_Inhand_Salary|Num_Bank_Accounts|Num_Credit_Card|Interest_Rate|Num_of_Loan|Type_of_Loan                                                |Delay_from_due_date|Num_of_Delayed_Payment|Changed_Credit_Limit|Num_Credit_Inquiries|Credit_Mix|Outstanding_Debt|Credit_Utilization_Ratio|Credit_History_Age   |Payment_of_Min_Amount|Total_EMI_per_month|Amount_invested_monthly|Payment_Behaviour              |Monthly_Balance|snapshot_date|
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+---------------------+---------------------+-------------------+-----------------------+-------------------------------+---------------+-------------+
|CUS_0x1037 |15989.085    |1086.4237            |5                |4              |2            |4          |Credit-Builder Loan, Auto Loan, Auto Loan, and Mortgage Loan|13                 |15                    |0.5                 |3                   |Good      |665.82          |40.6977                 |19 Years and 9 Months|No                   |33.79702           |80.46524               |Low_spent_Small_value_payments |284.38013      |2023-01-01   |
|CUS_0x1069 |58637.34     |4799.445             |4                |6              |10           |119        |Personal Loan, Auto Loan, and Not Specified                 |9                  |17                    |12.56               |5                   |Standard  |208.8           |25.233143               |30 Years and 8 Months|Yes                  |139.88501          |165.21062              |High_spent_Small_value_payments|434.84888      |2023-01-01   |
|CUS_0x114a |15305.46     |1230.455             |0                |7              |2            |2          |Student Loan, and Home Equity Loan                          |14                 |2                     |15.95               |0                   |Good      |642.42          |27.525112               |15 Years and 9 Months|No                   |20.301655          |64.77848               |Low_spent_Small_value_payments |327.96536      |2023-01-01   |
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+---------------------+---------------------+-------------------+-----------------------+-------------------------------+---------------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Annual_Income: float (nullable = true)
 |-- Monthly_Inhand_Salary: float (nullable = true)
 |-- Num_Bank_Accounts: integer (nullable = true)
 |-- Num_Credit_Card: integer (nullable = true)
 |-- Interest_Rate: integer (nullable = true)
 |-- Num_of_Loan: integer (nullable = true)
 |-- Type_of_Loan: string (nullable = true)
 |-- Delay_from_due_date: integer (nullable = true)
 |-- Num_of_Delayed_Payment: integer (nullable = true)
 |-- Changed_Credit_Limit: float (nullable = true)
 |-- Num_Credit_Inquiries: integer (nullable = true)
 |-- Credit_Mix: string (nullable = true)
 |-- Outstanding_Debt: float (nullable = true)
 |-- Credit_Utilization_Ratio: float (nullable = true)
 |-- Credit_History_Age: string (nullable = true)
 |-- Payment_of_Min_Amount: string (nullable = true)
 |-- Total_EMI_per_month: float (nullable = true)
 |-- Amount_invested_monthly: float (nullable = true)
 |-- Payment_Behaviour: string (nullable = true)
 |-- Monthly_Balance: float (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+------------------------------------------------------------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+---------------------+---------------------+-------------------+-----------------------+-------------------------------+---------------+-------------+
|Customer_ID|Annual_Income|Monthly_Inhand_Salary|Num_Bank_Accounts|Num_Credit_Card|Interest_Rate|Num_of_Loan|Type_of_Loan                                                                                                                  |Delay_from_due_date|Num_of_Delayed_Payment|Changed_Credit_Limit|Num_Credit_Inquiries|Credit_Mix|Outstanding_Debt|Credit_Utilization_Ratio|Credit_History_Age   |Payment_of_Min_Amount|Total_EMI_per_month|Amount_invested_monthly|Payment_Behaviour              |Monthly_Balance|snapshot_date|
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+------------------------------------------------------------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+---------------------+---------------------+-------------------+-----------------------+-------------------------------+---------------+-------------+
|CUS_0x10aa |114432.03    |9272.003             |1                |2              |7            |0          |NULL                                                                                                                          |9                  |9                     |7.98                |4                   |Good      |444.51          |39.014786               |21 Years and 6 Months|No                   |0.0                |101.6493               |High_spent_Large_value_payments|1065.5509      |2023-02-01   |
|CUS_0x113e |34476.68     |2715.0566            |6                |7              |24           |8          |Personal Loan, Student Loan, Personal Loan, Mortgage Loan, Student Loan, Not Specified, Auto Loan, and Debt Consolidation Loan|36                 |17                    |4.48                |11                  |Bad       |1976.63         |23.553509               |11 Years and 6 Months|Yes                  |171.17577          |10000.0                |Low_spent_Medium_value_payments|147.55739      |2023-02-01   |
|CUS_0x1140 |1.4532812E7  |914.15               |6                |10             |28           |6          |Credit-Builder Loan, Debt Consolidation Loan, Personal Loan, Mortgage Loan, Payday Loan, and Auto Loan                        |18                 |19                    |27.01               |14                  |Bad       |4128.98         |29.370855               |6 Years and 11 Months|Yes                  |24.906263          |80.86351               |Low_spent_Large_value_payments |255.64522      |2023-02-01   |
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+------------------------------------------------------------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+---------------------+---------------------+-------------------+-----------------------+-------------------------------+---------------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Annual_Income: float (nullable = true)
 |-- Monthly_Inhand_Salary: float (nullable = true)
 |-- Num_Bank_Accounts: integer (nullable = true)
 |-- Num_Credit_Card: integer (nullable = true)
 |-- Interest_Rate: integer (nullable = true)
 |-- Num_of_Loan: integer (nullable = true)
 |-- Type_of_Loan: string (nullable = true)
 |-- Delay_from_due_date: integer (nullable = true)
 |-- Num_of_Delayed_Payment: integer (nullable = true)
 |-- Changed_Credit_Limit: float (nullable = true)
 |-- Num_Credit_Inquiries: integer (nullable = true)
 |-- Credit_Mix: string (nullable = true)
 |-- Outstanding_Debt: float (nullable = true)
 |-- Credit_Utilization_Ratio: float (nullable = true)
 |-- Credit_History_Age: string (nullable = true)
 |-- Payment_of_Min_Amount: string (nullable = true)
 |-- Total_EMI_per_month: float (nullable = true)
 |-- Amount_invested_monthly: float (nullable = true)
 |-- Payment_Behaviour: string (nullable = true)
 |-- Monthly_Balance: float (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+-------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+----------------------+---------------------+-------------------+-----------------------+-------------------------------+---------------+-------------+
|Customer_ID|Annual_Income|Monthly_Inhand_Salary|Num_Bank_Accounts|Num_Credit_Card|Interest_Rate|Num_of_Loan|Type_of_Loan                                                             |Delay_from_due_date|Num_of_Delayed_Payment|Changed_Credit_Limit|Num_Credit_Inquiries|Credit_Mix|Outstanding_Debt|Credit_Utilization_Ratio|Credit_History_Age    |Payment_of_Min_Amount|Total_EMI_per_month|Amount_invested_monthly|Payment_Behaviour              |Monthly_Balance|snapshot_date|
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+-------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+----------------------+---------------------+-------------------+-----------------------+-------------------------------+---------------+-------------+
|CUS_0x10bb |60830.92     |5044.243             |0                |1              |11           |4          |Payday Loan, Home Equity Loan, Auto Loan, and Debt Consolidation Loan    |14                 |3                     |7.41                |0                   |_         |133.63          |38.7123                 |23 Years and 10 Months|No                   |159.79935          |404.0458               |Low_spent_Small_value_payments |230.57916      |2023-03-01   |
|CUS_0x10eb |28315.95     |2415.6626            |4                |7              |10           |NULL       |Student Loan, and Payday Loan                                            |8                  |8                     |10.34               |4                   |Good      |677.4           |26.912323               |20 Years and 5 Months |No                   |30.230997          |133.04883              |Low_spent_Small_value_payments |368.2864       |2023-03-01   |
|CUS_0x1132 |46268.4      |3983.7               |5                |4              |20           |NULL       |Student Loan, Debt Consolidation Loan, Student Loan, and Home Equity Loan|27                 |17                    |9.58                |9                   |_         |1447.57         |30.457222               |14 Years and 0 Months |Yes                  |103.77805          |230.94916              |High_spent_Small_value_payments|323.6428       |2023-03-01   |
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+-------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+----------------------+---------------------+-------------------+-----------------------+-------------------------------+---------------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Annual_Income: float (nullable = true)
 |-- Monthly_Inhand_Salary: float (nullable = true)
 |-- Num_Bank_Accounts: integer (nullable = true)
 |-- Num_Credit_Card: integer (nullable = true)
 |-- Interest_Rate: integer (nullable = true)
 |-- Num_of_Loan: integer (nullable = true)
 |-- Type_of_Loan: string (nullable = true)
 |-- Delay_from_due_date: integer (nullable = true)
 |-- Num_of_Delayed_Payment: integer (nullable = true)
 |-- Changed_Credit_Limit: float (nullable = true)
 |-- Num_Credit_Inquiries: integer (nullable = true)
 |-- Credit_Mix: string (nullable = true)
 |-- Outstanding_Debt: float (nullable = true)
 |-- Credit_Utilization_Ratio: float (nullable = true)
 |-- Credit_History_Age: string (nullable = true)
 |-- Payment_of_Min_Amount: string (nullable = true)
 |-- Total_EMI_per_month: float (nullable = true)
 |-- Amount_invested_monthly: float (nullable = true)
 |-- Payment_Behaviour: string (nullable = true)
 |-- Monthly_Balance: float (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+-------------------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+----------------------+---------------------+-------------------+-----------------------+------------------------------+---------------+-------------+
|Customer_ID|Annual_Income|Monthly_Inhand_Salary|Num_Bank_Accounts|Num_Credit_Card|Interest_Rate|Num_of_Loan|Type_of_Loan                                                                         |Delay_from_due_date|Num_of_Delayed_Payment|Changed_Credit_Limit|Num_Credit_Inquiries|Credit_Mix|Outstanding_Debt|Credit_Utilization_Ratio|Credit_History_Age    |Payment_of_Min_Amount|Total_EMI_per_month|Amount_invested_monthly|Payment_Behaviour             |Monthly_Balance|snapshot_date|
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+-------------------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+----------------------+---------------------+-------------------+-----------------------+------------------------------+---------------+-------------+
|CUS_0x1056 |16053.86     |1196.8217            |8                |6              |24           |5          |Student Loan, Student Loan, Not Specified, Personal Loan, and Debt Consolidation Loan|27                 |18                    |0.83                |12                  |Bad       |2107.76         |36.854668               |16 Years and 2 Months |Yes                  |44.86029           |154.06862              |Low_spent_Small_value_payments|210.75325      |2023-04-01   |
|CUS_0x11fc |38735.57     |3187.964             |2                |4              |3            |2          |Payday Loan, and Debt Consolidation Loan                                             |15                 |11                    |8.06                |2                   |Good      |800.94          |36.785755               |17 Years and 5 Months |No                   |43.943752          |125.365906             |Low_spent_Large_value_payments|419.48676      |2023-04-01   |
|CUS_0x1216 |20143.27     |1550.6058            |10               |8              |27           |2          |Not Specified, and Credit-Builder Loan                                               |44                 |15                    |9.44                |17                  |Standard  |1693.73         |36.301365               |10 Years and 10 Months|Yes                  |30.35921           |141.89656              |Low_spent_Small_value_payments|272.8048       |2023-04-01   |
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+-------------------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+----------------------+---------------------+-------------------+-----------------------+------------------------------+---------------+-------------+
only showing top 3 rows

root
 |-- Customer_ID: string (nullable = true)
 |-- Annual_Income: float (nullable = true)
 |-- Monthly_Inhand_Salary: float (nullable = true)
 |-- Num_Bank_Accounts: integer (nullable = true)
 |-- Num_Credit_Card: integer (nullable = true)
 |-- Interest_Rate: integer (nullable = true)
 |-- Num_of_Loan: integer (nullable = true)
 |-- Type_of_Loan: string (nullable = true)
 |-- Delay_from_due_date: integer (nullable = true)
 |-- Num_of_Delayed_Payment: integer (nullable = true)
 |-- Changed_Credit_Limit: float (nullable = true)
 |-- Num_Credit_Inquiries: integer (nullable = true)
 |-- Credit_Mix: string (nullable = true)
 |-- Outstanding_Debt: float (nullable = true)
 |-- Credit_Utilization_Ratio: float (nullable = true)
 |-- Credit_History_Age: string (nullable = true)
 |-- Payment_of_Min_Amount: string (nullable = true)
 |-- Total_EMI_per_month: float (nullable = true)
 |-- Amount_invested_monthly: float (nullable = true)
 |-- Payment_Behaviour: string (nullable = true)
 |-- Monthly_Balance: float (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+----------------------+---------------------+-------------------+-----------------------+--------------------------------+---------------+-------------+

In [61]:
# ─── Block 7: Union All into df_all ──────────────────────────────────────────
df_all = df_list[0]
for df in df_list[1:]:
    df_all = df_all.union(df)
print("Total rows:", df_all.count())

Total rows: 11974

In [62]:
# ─── Block 8: Validation Checks ──────────────────────────────────────────────
# 8a) Payment_of_Min_Amount values ≠ Yes/No
invalid_pay = df_all.filter(
    ~col("Payment_of_Min_Amount").isin("Yes", "No")
)
print("Invalid Payment_of_Min_Amount values:")
invalid_pay.select("Payment_of_Min_Amount").distinct().show()

# 8b) Interest_Rate out of [0,100]
ir_bad = df_all.filter((col("Interest_Rate") < 0) | (col("Interest_Rate") > 100))
print("Out-of-range Interest_Rate rows:")
ir_bad.select("Interest_Rate").distinct().show()

Invalid Payment_of_Min_Amount values:
+---------------------+
|Payment_of_Min_Amount|
+---------------------+
|                   NM|
+---------------------+

Out-of-range Interest_Rate rows:
+-------------+
|Interest_Rate|
+-------------+
|         1884|
|         4796|
|         4230|
|         4349|
|         2565|
|         2915|
|         1060|
|         4140|
|         4689|
|         5059|
|         2617|
|         2866|
|         4000|
|         3043|
|         2723|
|         2616|
|         4842|
|         2831|
|         1232|
|         2891|
+-------------+
only showing top 20 rows

In [63]:
# ─── Block 9: Count of Invalids & Nulls ──────────────────────────────────────
print("Count invalid Payment_of_Min_Amount:", invalid_pay.count())
print("Count out-of-range Interest_Rate:",   ir_bad.count())

# Null counts for these critical columns
df_all.select([
    _count(when(col(c).isNull(), c)).alias(c + "_nulls")
    for c in ["Payment_of_Min_Amount", "Credit_History_Age", "Interest_Rate"]
]).show()

Count invalid Payment_of_Min_Amount: 1380
Count out-of-range Interest_Rate: 258
+---------------------------+------------------------+-------------------+
|Payment_of_Min_Amount_nulls|Credit_History_Age_nulls|Interest_Rate_nulls|
+---------------------------+------------------------+-------------------+
|                          0|                       0|                  0|
+---------------------------+------------------------+-------------------+

In [64]:
# ─── Block 10: (Optional) Fix Interest_Rate anomalies now
df_all = df_all.withColumn(
    "Interest_Rate",
    when(col("Interest_Rate").between(0,100), col("Interest_Rate"))
    .otherwise(lit(0))
)
# leave Payment_of_Min_Amount & Credit_History_Age raw for Silver

In [66]:
# ─── Block: Count Invalid Payment_Behaviour Instances ─────────────────────────
from pyspark.sql.functions import col

# regex for any special character (not letter, digit, or space)
special_chars_pattern = r"[^A-Za-z0-9 ]"

# count rows where Payment_Behaviour contains special chars
invalid_pb_count = df_all.filter(col("Payment_Behaviour").rlike(special_chars_pattern)).count()

print(f"Number of invalid Payment_Behaviour entries: {invalid_pb_count}")

Number of invalid Payment_Behaviour entries: 0

In [46]:
# ─── Block 10: Label Out-of-Range & Count Nulls ─────────────────────────────
# e.g. Interest_Rate should be 0–100; anything outside → 0
df_all = df_all.withColumn(
    "Interest_Rate",
    when(col("Interest_Rate").between(0,100), col("Interest_Rate"))
    .otherwise(lit(0))
)
# count nulls per column
df_all.select([
    _count(when(col(c).isNull(), c)).alias(c + "_nulls")
    for c in df_all.columns
]).show(truncate=False)

+-----------------+-------------------+---------------------------+-----------------------+---------------------+-------------------+-----------------+------------------+-------------------------+----------------------------+--------------------------+--------------------------+----------------+----------------------+------------------------------+------------------------+---------------------------+-------------------------+-----------------------------+-----------------------+---------------------+-------------------+-------------------------------+--------------------------+
|Customer_ID_nulls|Annual_Income_nulls|Monthly_Inhand_Salary_nulls|Num_Bank_Accounts_nulls|Num_Credit_Card_nulls|Interest_Rate_nulls|Num_of_Loan_nulls|Type_of_Loan_nulls|Delay_from_due_date_nulls|Num_of_Delayed_Payment_nulls|Changed_Credit_Limit_nulls|Num_Credit_Inquiries_nulls|Credit_Mix_nulls|Outstanding_Debt_nulls|Credit_Utilization_Ratio_nulls|Credit_History_Age_nulls|Payment_of_Min_Amount_nulls|Total_EMI_per_month_nulls|Amount_invested_monthly_nulls|Payment_Behaviour_nulls|Monthly_Balance_nulls|snapshot_date_nulls|Credit_History_Age_Months_nulls|Paid_Min_Amount_Flag_nulls|
+-----------------+-------------------+---------------------------+-----------------------+---------------------+-------------------+-----------------+------------------+-------------------------+----------------------------+--------------------------+--------------------------+----------------+----------------------+------------------------------+------------------------+---------------------------+-------------------------+-----------------------------+-----------------------+---------------------+-------------------+-------------------------------+--------------------------+
|0                |0                  |0                          |0                      |0                    |0                  |596              |1368              |0                        |359                         |0                         |0                         |0               |0                     |0                             |0                       |0                          |0                        |0                            |0                      |0                    |0                  |0                              |0                         |
+-----------------+-------------------+---------------------------+-----------------------+---------------------+-------------------+-----------------+------------------+-------------------------+----------------------------+--------------------------+--------------------------+----------------+----------------------+------------------------------+------------------------+---------------------------+-------------------------+-----------------------------+-----------------------+---------------------+-------------------+-------------------------------+--------------------------+

# Fclickstream

 --------

In [84]:
# directory containing your feature CSVs
fe_dir   = "/app/datamart/bronze/clickstream/"
fe_paths = glob.glob(os.path.join(fe_dir, "*.csv"))
print("Found feature CSVs:", [os.path.basename(p) for p in fe_paths])

Found feature CSVs: ['bronze_feature_clickstream_2023_01_01.csv', 'bronze_feature_clickstream_2023_02_01.csv', 'bronze_feature_clickstream_2023_03_01.csv', 'bronze_feature_clickstream_2023_04_01.csv', 'bronze_feature_clickstream_2023_05_01.csv', 'bronze_feature_clickstream_2023_06_01.csv', 'bronze_feature_clickstream_2023_07_01.csv', 'bronze_feature_clickstream_2023_08_01.csv', 'bronze_feature_clickstream_2023_09_01.csv', 'bronze_feature_clickstream_2023_10_01.csv', 'bronze_feature_clickstream_2023_11_01.csv', 'bronze_feature_clickstream_2023_12_01.csv', 'bronze_feature_clickstream_2024_01_01.csv', 'bronze_feature_clickstream_2024_02_01.csv', 'bronze_feature_clickstream_2024_03_01.csv', 'bronze_feature_clickstream_2024_04_01.csv', 'bronze_feature_clickstream_2024_05_01.csv', 'bronze_feature_clickstream_2024_06_01.csv', 'bronze_feature_clickstream_2024_07_01.csv', 'bronze_feature_clickstream_2024_08_01.csv', 'bronze_feature_clickstream_2024_09_01.csv', 'bronze_feature_clickstream_2024_10_01.csv', 'bronze_feature_clickstream_2024_11_01.csv', 'bronze_feature_clickstream_2024_12_01.csv']

In [85]:
# ─── Block 2: Pandas-based Missing / Zero / Dtype Summary ─────────────────────
total_rows = 0

# Read first file to initialize
first_df = pd.read_csv(fe_paths[0]) if fe_paths else pd.DataFrame()
cols = first_df.columns
miss  = pd.Series(0, index=cols, dtype=int)
zeros = pd.Series(0, index=cols, dtype=int)
dtypes = first_df.dtypes.astype(str) if not first_df.empty else pd.Series(dtype=str)

for path in fe_paths:
    df = pd.read_csv(path)
    total_rows += len(df)
    # update dtypes only once (first file)
    # accumulate missing
    miss  += df.isna().sum()
    # accumulate zeros in numeric columns
    num   = df.select_dtypes(include=[np.number]).columns
    zeros[num] += (df[num] == 0).sum()

summary = pd.DataFrame({
    "dtype":   dtypes,
    "missing": miss,
    "zeros":   zeros,
})
summary["pct_missing"] = summary["missing"] / total_rows * 100

print(f"Processed {len(fe_paths)} files, {total_rows} total rows")
display(summary)

Processed 24 files, 215376 total rows

                dtype  missing  zeros  pct_missing
fe_1            int64        0    514          0.0
fe_2            int64        0    528          0.0
fe_3            int64        0    475          0.0
fe_4            int64        0    502          0.0
fe_5            int64        0    479          0.0
fe_6            int64        0    520          0.0
fe_7            int64        0    483          0.0
fe_8            int64        0    485          0.0
fe_9            int64        0    461          0.0
fe_10           int64        0    426          0.0
fe_11           int64        0    500          0.0
fe_12           int64        0    538          0.0
fe_13           int64        0    517          0.0
fe_14           int64        0    499          0.0
fe_15           int64        0    542          0.0
fe_16           int64        0    542          0.0
fe_17           int64        0    531          0.0
fe_18           int64        0    505          0.0
fe_19           int64        0    543          0.0
fe_20           int64        0    551          0.0
Customer_ID    object        0      0          0.0
snapshot_date  object        0      0          0.0

In [86]:
# ─── Block 3: Preview head() of the First File ─────────────────────────────────
if fe_paths:
    df0 = pd.read_csv(fe_paths[0])
    print(f"--- {os.path.basename(fe_paths[0])} head() ---")
    display(df0.head())
else:
    print("No feature CSVs found in", fe_dir)

--- bronze_feature_clickstream_2023_01_01.csv head() ---

,fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,fe_10,fe_11,fe_12,fe_13,fe_14,fe_15,fe_16,fe_17,fe_18,fe_19,fe_20,Customer_ID,snapshot_date
0,63,118,80,121,55,193,111,112,-101,83,164,105,-16,-81,-126,114,35,85,-73,76,CUS_0x1037,2023-01-01
1,-108,182,123,4,-56,27,25,-6,284,222,203,190,-14,-96,200,35,130,94,111,75,CUS_0x1069,2023-01-01
2,-13,8,87,166,214,-98,215,152,129,139,14,203,26,86,171,125,-130,354,17,302,CUS_0x114a,2023-01-01
3,-85,45,200,89,128,54,76,51,61,139,6,197,172,96,174,163,37,207,180,118,CUS_0x1184,2023-01-01
4,55,120,226,-86,253,97,107,68,103,126,34,12,76,43,183,159,-26,104,118,184,CUS_0x1297,2023-01-01

In [87]:
# ─── Block 4: Spark Session & Schema-Enforcement Function ────────────────────
spark = SparkSession.builder.appName("BronzeToSilverFeatures").getOrCreate()

def enforce_schema_features(df):
    """
    Cast fe_1…fe_20 to IntegerType (allowing negatives & positives),
    Customer_ID to StringType, snapshot_date to DateType.
    """
    for i in range(1, 21):
        df = df.withColumn(f"fe_{i}", col(f"fe_{i}").cast(IntegerType()))
    df = df.withColumn("Customer_ID", col("Customer_ID").cast(StringType()))
    df = df.withColumn("snapshot_date", to_date(col("snapshot_date"), "yyyy-MM-dd"))
    return df

In [88]:
# ─── Block 5: Read & Clean All CSVs into a List ──────────────────────────────
df_list = []
for path in fe_paths:
    raw   = spark.read.csv(path, header=True, inferSchema=False)
    clean = enforce_schema_features(raw)
    df_list.append(clean)

In [89]:
# ─── Block 6: Preview Schema & Sample Rows ──────────────────────────────────
for df in df_list:
    df.printSchema()
    df.show(3, truncate=False)

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|63  |118 |80  |121 |55  |193 |111 |112 |-101|83   |164  |105  |-16  |-81  |-126 |114  |35   |85   |-73  |76   |CUS_0x1037 |2023-01-01   |
|-108|182 |123 |4   |-56 |27  |25  |-6  |284 |222  |203  |190  |-14  |-96  |200  |35   |130  |94   |111  |75   |CUS_0x1069 |2023-01-01   |
|-13 |8   |87  |166 |214 |-98 |215 |152 |129 |139  |14   |203  |26   |86   |171  |125  |-130 |354  |17   |302  |CUS_0x114a |2023-01-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 3 rows

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|55  |96  |74  |171 |-69 |-103|86  |178 |42  |113  |100  |183  |39   |179  |161  |71   |208  |-7   |129  |206  |CUS_0x1037 |2023-02-01   |
|100 |-115|50  |246 |140 |160 |122 |112 |14  |221  |-82  |284  |57   |146  |120  |67   |-4   |139  |-26  |-51  |CUS_0x1069 |2023-02-01   |
|142 |106 |143 |155 |153 |121 |64  |17  |-2  |208  |44   |-17  |118  |-55  |-47  |93   |50   |173  |50   |274  |CUS_0x114a |2023-02-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 3 rows

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|232 |203 |-71 |86  |243 |12  |79  |122 |103 |178  |273  |96   |201  |37   |96   |63   |98   |69   |257  |3    |CUS_0x1037 |2023-03-01   |
|-31 |2   |19  |-52 |176 |-24 |158 |138 |186 |53   |-1   |72   |196  |192  |204  |144  |-105 |4    |169  |98   |CUS_0x1069 |2023-03-01   |
|139 |142 |127 |167 |29  |-42 |143 |151 |60  |97   |111  |14   |-132 |56   |150  |-108 |115  |109  |202  |138  |CUS_0x114a |2023-03-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 3 rows

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|9   |-29 |-8  |116 |198 |68  |79  |61  |113 |91   |36   |179  |17   |219  |89   |136  |-25  |180  |109  |118  |CUS_0x1037 |2023-04-01   |
|104 |92  |101 |136 |315 |169 |420 |-18 |135 |46   |61   |119  |84   |21   |105  |118  |20   |127  |43   |251  |CUS_0x1069 |2023-04-01   |
|164 |47  |36  |144 |19  |127 |67  |197 |286 |217  |257  |10   |92   |14   |89   |148  |145  |143  |93   |72   |CUS_0x114a |2023-04-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 3 rows

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|203 |75  |223 |88  |188 |164 |82  |18  |195 |50   |276  |50   |4    |-41  |184  |150  |212  |139  |1    |46   |CUS_0x1037 |2023-05-01   |
|-4  |72  |151 |79  |170 |181 |20  |335 |320 |191  |8    |106  |249  |197  |209  |-19  |202  |61   |43   |124  |CUS_0x1069 |2023-05-01   |
|150 |165 |96  |21  |-45 |109 |196 |162 |188 |233  |13   |182  |-177 |250  |97   |129  |-152 |120  |185  |162  |CUS_0x114a |2023-05-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 3 rows

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|145 |108 |78  |-33 |212 |62  |-46 |135 |-6  |96   |21   |-9   |-82  |79   |-72  |184  |114  |281  |-45  |51   |CUS_0x1037 |2023-06-01   |
|14  |155 |70  |45  |233 |-121|174 |159 |3   |154  |18   |141  |119  |275  |116  |166  |154  |81   |75   |163  |CUS_0x1069 |2023-06-01   |
|305 |197 |101 |-41 |-30 |60  |266 |66  |110 |-65  |-35  |22   |67   |103  |-3   |309  |233  |149  |185  |68   |CUS_0x114a |2023-06-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 3 rows

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|40  |90  |231 |136 |239 |273 |106 |178 |90  |202  |52   |205  |44   |134  |154  |108  |29   |108  |141  |260  |CUS_0x1037 |2023-07-01   |
|-26 |37  |87  |26  |173 |142 |164 |73  |207 |138  |76   |142  |197  |139  |297  |94   |95   |272  |252  |189  |CUS_0x1069 |2023-07-01   |
|35  |230 |102 |146 |-40 |59  |15  |115 |-6  |116  |-32  |214  |256  |206  |49   |-5   |137  |118  |89   |207  |CUS_0x114a |2023-07-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 3 rows

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|2   |128 |115 |-31 |106 |144 |69  |200 |16  |248  |-4   |160  |33   |112  |104  |97   |181  |11   |114  |260  |CUS_0x1037 |2023-08-01   |
|8   |194 |-24 |93  |-128|242 |122 |251 |2   |213  |194  |47   |45   |-91  |240  |-50  |182  |105  |167  |55   |CUS_0x1069 |2023-08-01   |
|-44 |-1  |-26 |-17 |88  |222 |113 |209 |285 |-60  |-41  |40   |189  |126  |185  |263  |-77  |159  |-98  |95   |CUS_0x114a |2023-08-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 3 rows

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|221 |226 |-112|49  |226 |209 |44  |123 |244 |106  |0    |-13  |-102 |225  |125  |74   |189  |-64  |170  |57   |CUS_0x1037 |2023-09-01   |
|83  |141 |184 |54  |204 |76  |180 |-41 |147 |238  |94   |65   |108  |199  |-33  |193  |85   |144  |67   |-124 |CUS_0x1069 |2023-09-01   |
|40  |96  |34  |3   |101 |185 |158 |105 |79  |97   |45   |145  |-49  |188  |-38  |75   |121  |158  |39   |49   |CUS_0x114a |2023-09-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 3 rows

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|168 |176 |119 |190 |151 |-17 |-17 |-46 |172 |56   |244  |114  |16   |-53  |110  |246  |29   |241  |67   |25   |CUS_0x1037 |2023-10-01   |
|139 |-68 |142 |88  |185 |202 |57  |-103|108 |158  |228  |148  |308  |57   |80   |133  |127  |87   |102  |-58  |CUS_0x1069 |2023-10-01   |
|253 |68  |0   |-16 |221 |104 |43  |237 |168 |186  |-49  |228  |225  |90   |273  |-40  |78   |248  |-3   |138  |CUS_0x114a |2023-10-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 3 rows

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|63  |247 |155 |46  |61  |229 |229 |107 |129 |395  |226  |160  |214  |-74  |200  |-129 |79   |128  |20   |230  |CUS_0x1037 |2023-11-01   |
|76  |107 |135 |104 |188 |412 |266 |165 |104 |117  |81   |123  |-53  |146  |-114 |108  |290  |131  |288  |73   |CUS_0x1069 |2023-11-01   |

In [90]:
# ─── Block 7: Union All & Row Count ──────────────────────────────────────────
df_all = df_list[0]
for df in df_list[1:]:
    df_all = df_all.union(df)
print("Total rows across all feature files:", df_all.count())

Total rows across all feature files: 215376

In [91]:
# ─── Block 8: Numeric Summary of Features ────────────────────────────────────
df_all.select([col(f"fe_{i}") for i in range(1,21)]).describe().show()

+-------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----------------+------------------+------------------+------------------+------------------+------------------+
|summary|              fe_1|              fe_2|              fe_3|              fe_4|              fe_5|              fe_6|              fe_7|              fe_8|              fe_9|             fe_10|             fe_11|             fe_12|             fe_13|             fe_14|            fe_15|             fe_16|             fe_17|             fe_18|             fe_19|             fe_20|
+-------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----------------+------------------+------------------+------------------+------------------+------------------+
|  count|            215376|            215376|            215376|            215376|            215376|            215376|            215376|            215376|            215376|            215376|            215376|            215376|            215376|            215376|           215376|            215376|            215376|            215376|            215376|            215376|
|   mean|101.41479552039225|103.09619456206819|104.33370941980536|105.64850308298047|106.99667558130896|103.23592229403462| 107.0703374563554|110.71872446326425|114.40635446846446|117.77579674615556|   99.615537478642| 99.82368044721788|  100.420803617859|100.02580138919842|99.60038258673204| 99.86083407622019|100.12942481984993|100.12513929128593|  100.341161503603|100.04625863605973|
| stddev| 99.83359392844196| 99.93000203749267|100.59986549187698|100.32606477046154| 100.6936066585856|100.27038751891196|100.32326515826558|100.24369781781941|100.18613852691665|100.80768608991768|100.33542808342577|100.59117511972622|100.88182648131865|101.07037079177513|101.1459061777699|100.75187641058744|  101.298428118751| 102.2315866800892|102.66680374052837|103.58935787523677|
|    min|              -378|              -356|              -399|              -307|              -343|              -321|              -368|              -361|              -328|              -317|              -375|              -344|              -355|              -394|             -351|              -342|              -329|              -344|              -401|              -354|
|    max|               541|               560|               583|               562|               570|               565|               537|               573|               577|               537|               613|               550|               530|               583|              597|               554|               516|               551|               560|               547|
+-------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----------------+------------------+------------------+------------------+------------------+------------------+

In [92]:
# ─── Block 9: Duplicate Checks on Customer_ID & snapshot_date ────────────────
total = df_all.count()
for key in ["Customer_ID", "snapshot_date"]:
    uniq = df_all.select(key).distinct().count()
    print(f"{key}: {total - uniq} duplicates")

Customer_ID: 206402 duplicates
snapshot_date: 215352 duplicates

In [96]:
# ─── Block 10: Count Nulls & Zeroes in All Columns ───────────────────────────
# nulls per column
null_exprs = [ _count(col(c).isNull().cast("int")).alias(c + "_nulls")
               for c in df_all.columns ]
# zero counts for features
zero_exprs = [ _count((col(f"fe_{i}") == 0).cast("int")).alias(f"fe_{i}_zeros")
               for i in range(1,21) ]

df_all.select(null_exprs + zero_exprs).show(truncate=False)

+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------------+-------------------+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+
|fe_1_nulls|fe_2_nulls|fe_3_nulls|fe_4_nulls|fe_5_nulls|fe_6_nulls|fe_7_nulls|fe_8_nulls|fe_9_nulls|fe_10_nulls|fe_11_nulls|fe_12_nulls|fe_13_nulls|fe_14_nulls|fe_15_nulls|fe_16_nulls|fe_17_nulls|fe_18_nulls|fe_19_nulls|fe_20_nulls|Customer_ID_nulls|snapshot_date_nulls|fe_1_zeros|fe_2_zeros|fe_3_zeros|fe_4_zeros|fe_5_zeros|fe_6_zeros|fe_7_zeros|fe_8_zeros|fe_9_zeros|fe_10_zeros|fe_11_zeros|fe_12_zeros|fe_13_zeros|fe_14_zeros|fe_15_zeros|fe_16_zeros|fe_17_zeros|fe_18_zeros|fe_19_zeros|fe_20_zeros|
+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------------+-------------------+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+
|215376    |215376    |215376    |215376    |215376    |215376    |215376    |215376    |215376    |215376     |215376     |215376     |215376     |215376     |215376     |215376     |215376     |215376     |215376     |215376     |215376           |215376             |215376    |215376    |215376    |215376    |215376    |215376    |215376    |215376    |215376    |215376     |215376     |215376     |215376     |215376     |215376     |215376     |215376     |215376     |215376     |215376     |
+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------------+-------------------+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+

In [98]:
df_all.head(5)

[Row(fe_1=63, fe_2=118, fe_3=80, fe_4=121, fe_5=55, fe_6=193, fe_7=111, fe_8=112, fe_9=-101, fe_10=83, fe_11=164, fe_12=105, fe_13=-16, fe_14=-81, fe_15=-126, fe_16=114, fe_17=35, fe_18=85, fe_19=-73, fe_20=76, Customer_ID='CUS_0x1037', snapshot_date=datetime.date(2023, 1, 1)),
 Row(fe_1=-108, fe_2=182, fe_3=123, fe_4=4, fe_5=-56, fe_6=27, fe_7=25, fe_8=-6, fe_9=284, fe_10=222, fe_11=203, fe_12=190, fe_13=-14, fe_14=-96, fe_15=200, fe_16=35, fe_17=130, fe_18=94, fe_19=111, fe_20=75, Customer_ID='CUS_0x1069', snapshot_date=datetime.date(2023, 1, 1)),
 Row(fe_1=-13, fe_2=8, fe_3=87, fe_4=166, fe_5=214, fe_6=-98, fe_7=215, fe_8=152, fe_9=129, fe_10=139, fe_11=14, fe_12=203, fe_13=26, fe_14=86, fe_15=171, fe_16=125, fe_17=-130, fe_18=354, fe_19=17, fe_20=302, Customer_ID='CUS_0x114a', snapshot_date=datetime.date(2023, 1, 1)),
 Row(fe_1=-85, fe_2=45, fe_3=200, fe_4=89, fe_5=128, fe_6=54, fe_7=76, fe_8=51, fe_9=61, fe_10=139, fe_11=6, fe_12=197, fe_13=172, fe_14=96, fe_15=174, fe_16=163, fe_17=37, fe_18=207, fe_19=180, fe_20=118, Customer_ID='CUS_0x1184', snapshot_date=datetime.date(2023, 1, 1)),
 Row(fe_1=55, fe_2=120, fe_3=226, fe_4=-86, fe_5=253, fe_6=97, fe_7=107, fe_8=68, fe_9=103, fe_10=126, fe_11=34, fe_12=12, fe_13=76, fe_14=43, fe_15=183, fe_16=159, fe_17=-26, fe_18=104, fe_19=118, fe_20=184, Customer_ID='CUS_0x1297', snapshot_date=datetime.date(2023, 1, 1))]

In [99]:
# ─── Block 11: Integrity Check: Non-Integer Floats or Unparsable Strings ─────
null_counts  = {f"fe_{i}": 0 for i in range(1,21)}
float_counts = {f"fe_{i}": 0 for i in range(1,21)}

for i in range(1,21):
    fe = f"fe_{i}"
    nulls = df_all.filter(col(fe).isNull()).count()
    floats= df_all.filter(col(fe).isNotNull() & (col(fe) != floor(col(fe)))).count()
    null_counts[fe]  = nulls
    float_counts[fe] = floats

print(f"{'Feature':<6} {'Unparsable (nulls)':>20} {'Non-int Floats':>16}")
for i in range(1,21):
    fe = f"fe_{i}"
    print(f"{fe:<6} {null_counts[fe]:>20} {float_counts[fe]:>16}")

print(f"\nTotal unparsable: {sum(null_counts.values())}")
print(f"Total non-int floats: {sum(float_counts.values())}")

Feature   Unparsable (nulls)   Non-int Floats
fe_1                      0                0
fe_2                      0                0
fe_3                      0                0
fe_4                      0                0
fe_5                      0                0
fe_6                      0                0
fe_7                      0                0
fe_8                      0                0
fe_9                      0                0
fe_10                     0                0
fe_11                     0                0
fe_12                     0                0
fe_13                     0                0
fe_14                     0                0
fe_15                     0                0
fe_16                     0                0
fe_17                     0                0
fe_18                     0                0
fe_19                     0                0
fe_20                     0                0

Total unparsable: 0
Total non-int floats: 0

In [ ]:
for d in dates_str_lst:
    gold_feat.build_feature_gold(d, silver_root_directory, gold_feature_directory, spark, FEEDS)

In [ ]:
print('feature partitions:', len(glob.glob(gold_feature_directory+'*.parquet')))